liip_theme:
    resource: "@LiipThemeBundle/Resources/config/routing.xml"
    prefix: /theme

client:
    resource: "@ClientWebsiteBundle/Resources/config/routing.yml"

sulu_media:
    resource: "@SuluMediaBundle/Resources/config/routing_website.yml"
