liip_theme:
    resource: "@LiipThemeBundle/Resources/config/routing.xml"
    prefix: /theme

sulu_media:
    resource: "@SuluMediaBundle/Resources/config/routing_website.yml"

client_website:
    type: portal
    resource: "@ClientWebsiteBundle/Resources/config/routing.yml"

client_website_security:
    resource: "@ClientWebsiteBundle/Resources/config/routing_security.yml"

sulu_website:
    resource: "@SuluWebsiteBundle/Resources/config/routing_website.yml"
