security:
    session_fixation_strategy: none

    access_decision_manager:
        strategy: affirmative

    encoders:
        Sulu\Bundle\SecurityBundle\Entity\User:
            algorithm: sha512
            iterations: 5000
            encode_as_base64: false

    providers:
        sulu:
            id: sulu_security.user_repository

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }

    firewalls:
        website:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: website_login
                check_path: website_login_check
            logout:
                path: /logout
                target: /login
